DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE AUTHORS(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
);

CREATE TABLE GENRES(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
);

CREATE TABLE BOOKS(
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  TITLE VARCHAR(255),
  AUTHOR_ID INT,
  GENRE_ID INT,
  foreign key (AUTHOR_ID) references AUTHORS(ID),
  foreign key (GENRE_ID) references GENRES(ID),
)